export * from './About';
export * from './canvas';
export * from './Contact';
export * from './Experience';
export * from './Hero';
export * from './Navbar';
export * from './Projects';
export * from './ResumeButton';
export * from './Services'
export * from './SocialMedia';
export * from './Tech';
